### ISSUE TITLE
Fails when __file__ exists and has .dll extension

### ISSUE THREAD

**Issue by GadgetSteve** [albertosottile/py2exe#32] opened 2019-12-02 07:25 UTC
Branch 3.8 version Latest commit 1ec361d on Oct 12 downloaded as zip and pip installed.

Trying to build a project which includes pywintypes raises an error:

>   File "C:\Python38\lib\site-packages\py2exe\mf3.py", line 708, in __code__
>     raise RuntimeError("should read __file__ to get the source???")
> RuntimeError: should read __file__ to get the source???

Debugging this the value of __file__ in this case is:   `'c:\\Python38\\lib\\site-packages\\pywin32_system32\\pywintypes38.dll'` which obviously fails the test `__file__.endswith(".pyd")` on line 706.

**Comment by DirkOsswald** [comment] 2019-12-16 10:37
Had the same problem. Fixed it, see attached patch. 
Donnow how to commit or pull or whatever to this git stuff. Please let me know how to properly give code feedback
[py2exe-add-dll-support.zip](https://github.com/albertosottile/py2exe/files/3967572/py2exe-add-dll-support.zip)

**Comment by albertosottile** [comment] 2020-10-24 12:39
`pywin32` is included in the CI/CD test routine and it is working well in the 0.10.0.x tree without this fix. I would encourage you to try again with the latest version (0.10.0.2). For the moment, I am closing this. Please feel free to reopen anytime.

**Closed by albertosottile** 2020-10-24 12:39 UTC

**Comment by lambacck** [comment] 2020-12-31 22:00
@albertosottile This still seems to be broken on 0.10.1.0. Locally I'm seeing the issues listed above with pywintypes38.dll and pythoncom38.dll.

**Comment by lambacck** [comment] 2020-12-31 23:05
Looks like it's they are getting picked up twice, here with a patch I made to make the above mentioned issue work and let it be a  pyd:
```
Copy c:\python38\lib\site-packages\pywin32_system32\pywintypes38.dll to dist\pywintypes.pyd
Copy C:\WINDOWS\SYSTEM32\pythoncom38.dll to dist\pythoncom.pyd
```
and again at the end explicitly picking up the ExtensionDLL:
```
Copy ExtensionDLL c:\python38\lib\site-packages\pywin32_system32\pywintypes38.dll to dist\
Copy ExtensionDLL C:\WINDOWS\SYSTEM32\pythoncom38.dll to dist\
```

Maybe there is something up with a pip installed pywin32 instead of a installer installed pywin32?

**Comment by albertosottile** [comment] 2021-01-02 09:19
Interesting... I am not sure I understand what you did here. What I understand is that:
- you patched your copy of `py2exe` to rename (some/all?) the `.pyd` file(s) into a `.dll` when bundling those
- when you try to build a project with `pywin32`, this results in having **both** the DLL and the PYD in your bundle
- the bundled executable does/does not run? This is not clear to me.

Now, about the duplicate issue: not having a duplicate entry (please mind that those are not exactly duplicates but files with different extensions and also, in principle, different purposes in the bundle) was exactly the reason why I was against putting this patch in `py2exe`. The build chain should identify the DLL and copy it in the bundle, without any renaming. This is what is happening in the last two lines that you report here and it is also what is happening in the CI test:
```
Copy ExtensionDLL C:\Python38\Lib\site-packages\pywin32_system32\pywintypes38.dll to dist\
Copy ExtensionDLL C:\Python38\Lib\site-packages\pywin32_system32\pythoncom38.dll to dist\
```

About the patch you applied, I do not understand why you needed that. It seems that the DLLs are picked up by `py2exe` as `ExtensionDLL` so, the libraries are imported. Did you experience the `RuntimeError` described before without this patch? If so, it would be very interesting to know why you see this error whereas I do not, neither in CI nor in my local tests...

Finally, about the installer version of `pywin32`: I honestly do not know and I would strongly encourage you to use PyPI to manage your dependencies. It seems clear that the installer puts some libraries under ` C:\WINDOWS\SYSTEM32\` whereas the wheel does not.  Nevertheless, it seems to me that `pythoncom38.dll` is correctly picked up by the DLL copying system in `py2exe` so, I would say the different path does not pose an issue on that part. It might be that it affects the module finder somehow, though, and causes the `RuntimeError` originally mentioned in this issue. It would be great if you could uninstall py2exe from the installer, reinstall it from PyPI, and try again to reproduce this issue.

**Comment by albertosottile** [comment] 2021-01-04 09:34
The upcoming version 0.10.2.0 will introduce a new module finder that, in principle, should not trigger this issue anymore. Preliminary wheels for this version can be found on Bintray here: https://bintray.com/py2exe/py2exe/py2exe/0.10.2.0#files

@GadgetSteve @DirkOsswald @lambacck It would be great if you could install this version, repeat your tests with it, and report here if you still experience this issue. Thanks for your time.

**Comment by lambacck** [comment] 2021-01-24 19:53
@albertosottile It builds successfully and I get pywintype38.dll but it won't import when I run the resulting service with debug:
```
>wsgisvc.exe
Traceback (most recent call last):
  File "boot_service.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "win32serviceutil.pyc", line 10, in <module>
ModuleNotFoundError: No module named 'pywintypes'
```

**Comment by albertosottile** [comment] 2021-01-24 20:09
I would say this is a very different issue from the one described here. Please open another one, preferably with a minimal script and `setup.py` file that I can use to reproduce the error. Thanks.
