### ISSUE TITLE
Impossible to include pywin32 pythoncom in a project

### ISSUE THREAD

**Issue by leonardder** [albertosottile/py2exe#11] opened 2019-06-04 12:45 UTC
I stumbled upon this issue while working on NVDA. For us, it is no longer that much of a problem, since we decided to stop using pywin32.

Pywin32 has a library pythoncom, which if imported, is magically changed into a module referencing pythoncom37.dll (on python 3.7). However, this conflicts with runtime.Runtime.copy_files where for every python module without code, an assertion is made for the .pyd extension:

```
                if hasattr(mod, "__file__"):
                    assert mod.__file__.endswith(EXTENSION_SUFFIXES[0])
```

It looks like distutils_buildexe contains some commented out code that handles these cases correctly, but this doesn't seem to have been ported to the Python 3 version.

**Comment by albertosottile** [comment] 2019-06-04 18:28
Thanks for reporting this. IIRC, in the beginning, EXTENSION_SUFFIXES was manually adjusted to include also `.dll`, but that was later removed because it went against the Python specifications. The best approach would probably be to restore the code in `distutils_buildexe.plot_finalize` that manually loaded these dlls for those two packages. I will try all this when I have some spare time.

**Comment by emaimone** [comment] 2019-09-07 20:32
any progress on this bug? I need to port some apps that use pywin32 to 3.7 and this version 0.9.3.1 is my hope.
Tks

**Comment by albertosottile** [comment] 2019-09-08 10:09
I implemented a functional test for pywin32 and I am now unable to reproduce this issue. 
I used [this code](https://github.com/albertosottile/py2exe/blob/pywitest/tests/functional/pywin32_test/pywin32_test.py)  with [this setup.py file](https://github.com/albertosottile/py2exe/blob/pywitest/tests/functional/pywin32_test/setup.py) as test stand.

The test passes and these two lines are printed in the log during the building of the bundle (e.g for `cp37-win32`, [link to the full CI logs](https://ci.appveyor.com/project/albertosottile/py2exe/builds/27260533)):
```
Copy ExtensionDLL C:\Python37\lib\site-packages\pywin32_system32\pythoncom37.dll to dist\
Copy ExtensionDLL C:\Python37\lib\site-packages\pywin32_system32\pywintypes37.dll to dist\
```

Since I have not recently changed the code related to DLLs in py2exe, I am not sure of the actual status of this bug.  

@leonardder @emaimone Could you please download the latest wheels [from here](https://bintray.com/alby128/py2exe/py2exe/0.9.3.2/view/files?sort=name&order=asc#files/) and test them again in your setups? Please let me know if you are still able to reproduce this bug, either with my test stand or with your code.

**Comment by emaimone** [comment] 2019-09-09 20:55
@albertosottile version 0.9.3.2 correctly copied pythoncom37.dll to the distribution folder, but I might have misunderstood @leonardder post. 
I am actually trying to generate a COM server (setup.py file below). Neither versions 0.9.3.1 or 0.9.3.2 are generating it.
I can upload a complete code snippet in github if you want to replicate the issue.
Please let me know
Thank you
Enzo

`# setup.py
from distutils.core import setup
import py2exe

setup(name="NAFCOMBridge",
          com_server=["NAF-COM-bridge-v8"],
)`

**Comment by albertosottile** [comment] 2019-09-10 06:00
@emaimone Please, create a new issue with a detailed description of your problem and a minimal code example that can be used to reproduce it.

@leonardder I am closing this as I am assuming that is fixed now (even if I am not sure how). Please feel free to reopen this issue if you see it again.

**Closed by albertosottile** 2019-09-10 06:00 UTC
Labels: requires user input, unable to reproduce
