### ISSUE TITLE
Bundle everything into an EXE file using bundle_files=1 option

### ISSUE THREAD

**Issue by ivan2033** [albertosottile/py2exe#35] opened 2019-12-17 09:40 UTC
Hi,

We have moved our code from python 2 to python 3 and wanted to create our program EXE file using py2xe because it is faster than pyinstaller when launching. Thanks for making it possible to work in newer python 3 versions.

I am trying to generate a very very basic ".py" and I am able to generate an EXE file, but some DLLs are out of the EXE file. I am using "bundle_files = 1" in setup options. 

Is it not possible now to bundle everything into an EXE file?

Thanks in advance,
Iván

**Comment by albertosottile** [comment] 2019-12-18 21:04
Hi, thanks for reporting this issue. As I stated some times in this repository, py2exe is quite a large project with a lot of options, and I am not able to maintain them all as I would like to. Personally, I never used the `bundle_files = 1` option, so I cannot tell you right away if that feature is still working in the latest versions. 

That being said, I am willing to investigate this bug and perhaps implement a minimal test in the CI /CD chain to retain this functionality. Could you provide me a minimal working code (`setup.py` and main Python script) to reproduce this bug?

**Comment by ivan2033** [comment] 2019-12-19 06:56
Yes, of course. I tried first with a very simple example:

Main.py
--------
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os

f = open('mylog.log', 'w')
f.write('Hello world')
f.close()

setup.py
--------
#!/usr/bin/python
# -*- coding: utf-8 -*-

from distutils.core import setup 
import py2exe

mainfile = r'C:\Main.py'
exefile = 'Main'

setup(name="Main", 
    version='0.0', 
    description="Main script", 
    scripts=[mainfile],
    windows=[{"script":mainfile,
              'company_name' : "Company (c) 2019", 
              'copyright' : "Company (c) 2019",
              #'uac_info': "requireAdministrator",
              'dest_base' : exefile}],
              #"icon_resources":[(0, icon_file)]}],
    data_files = [],
    options={"py2exe": {"unbuffered": True,
                        "optimize": 2, 
                        "bundle_files": 1, 
                        "compressed": False, 
                        "includes": [],
                        "excludes" : [],
                        "packages": [],
                        "dll_excludes": []},},
    zipfile=None)

The output is as follows:
![dist](https://user-images.githubusercontent.com/8638645/71151536-3faa7180-2234-11ea-8d38-7ccb87c54290.png)

Until now, we were working with python2 and everything was packeted inside de EXE file using bundle_files=1. That was very convinient for use in order to use a portable instalation. I do not know if this has changed now with newer py2exe versions.

Thanks for replying so fast.
Best regards.

**Comment by albertosottile** [comment] 2020-10-24 13:34
I think the setting has been changed during the transition to Python 3. Now the setting you are looking for is `"bundle_files": 0`. I tested your script and setup files with this option and I can confirm it works as expected. With the option set to `1`, all the dependencies **except for external DLLs** are embedded in the executable, which is the behavior you were witnessing. The relevant docstrings are here: https://github.com/albertosottile/py2exe/blob/4c524b954183087d7374c79cfd2cd3caadebebf1/py2exe/setup_template.py#L132-L142

It is worth to mention that decreasing the value of `bundle_files` can cause more errors when importing several packages. Some of these are caught by the hook systems, others will just fail at execution time. 

Since the basic feature is still working as expected, I am closing this issue now. Please feel free to reopen it anytime, if needed.

**Closed by albertosottile** 2020-10-24 13:34 UTC
Labels: requires user input
