### ISSUE TITLE
IndexError: tuple index out of range on 0.9.2.2 and 0.9.3.0 py2exe with Python 3.6.

### ISSUE THREAD

**Issue by woody544** [albertosottile/py2exe#5] opened 2019-04-17 21:13 UTC
Thanks for working to get py2exe working with Python 3.5-3.7!! 

I was hoping that your version would solve my problem with py2exe. However, I am getting the same IndexError I had running with py2exe 0.9.2.2 and Python 3.6 and Windows 10. I have VS Community 2017.  I don't have any immediate ideas to offer now, as I have been fighting this error in py2exe for some time. I have been working between Python 2.7, 3.4, 3.6, and 3.7 and in addition to py2exe, with pyinstaller, and cx_Freeze. Along the way I realized the issues with the versions of Python 3 - that they are quite different. I am determined, and I think getting closer, but still not successful. So I am sharing both py2exe versions tracebacks (and my setup.py code) in case you can see something there that is useful for this effort. Each is separated by #######.

My setup.py file code:

`from distutils.core import setup
import py2exe, sys, os
import glob

sys.argv.append('py2exe')

setup(
    options = {'py2exe': {'bundle_files': 3, 'compressed': True}},
    windows = [{'script': "main.py"}],
    data_files = ['C:/WINDOWS/system32/OLEAUT32.dll','C:/WINDOWS/system32/USER32.dll', 'C:/WINDOWS/system32/IMM32.dll',
   'C:/WINDOWS/system32/SHELL32.dll', 'C:/WINDOWS/system32/KERNEL32.dll',
   'C:/WINDOWS/system32/COMDLG32.dll', 'C:/WINDOWS/system32/COMCTL32.dll',
   'C:/WINDOWS/system32/ADVAPI32.dll', 'C:/WINDOWS/system32/WS2_32.dll',
   'C:/WINDOWS/system32/GDI32.dll', 'C:/WINDOWS/system32/VERSION.dll',
   'C:/WINDOWS/system32/ole32.dll',("Microsoft.VC120.CRT", glob.glob(r'C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/redist/x86/Microsoft.VC120.CRT/*.*'))],
    zipfile = None,
)
`
#######

The tracebacks are not identical:

Running in VS command prompt with  py2exe 0.9.3.0 and Python 3.6, in my apptest folder:
command:
E:\A_ONE_CODE\4-6-19-AppBuildingTest\py2exe>py -3.6 -m py2exe setup.py

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\__main__.py", line 8, in <module>
    build_exe.main()
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\build_exe.py", line 141, in main
    builder.analyze()
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range

#######

Running in Idle with  py2exe 0.9.2.2 and Python 3.6, in apptest folder E:\A_ONE_CODE\4-6-19-AppBuildingTest\py2exe>

On the IDLE toolbar: hit 'Run' => 'Run Module' on open setup.py file

Traceback (most recent call last):
  File "E:\A_ONE_CODE\4-6-19-AppBuildingTest\py2exe\setup.py", line 16, in <module>
    zipfile = None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range

**Comment by albertosottile** [comment] 2019-04-25 08:13
Without a copy of the `main.py` script is hard for me to actually diagnose this issue. If you could provide it, that would be perfect, otherwise a minimal working example that reproduces the bug would also be great. Thanks for reporting this.

**Comment by albertosottile** [comment] 2019-04-26 16:05
I gave a better look at the tracebacks and there is something that puzzles me.
`yield "store", (names[oparg],)` is not at line 417 in 0.9.3.0, but at line 466 instead. Additionally, that line is in a branch that should not be executed on Python 3.4+ (I will probably remove that code in future releases).

So, I would double check which Python version you are actually running on your prompt, and also if the older versions of py2exe were completely uninstalled before this test.

**Comment by albertosottile** [comment] 2019-05-14 14:05
I am going to close this since I am unable to reproduce it and I did not receive further information. Please feel free to reopen it when you are able to provide relevant data.

**Closed by albertosottile** 2019-05-14 14:05 UTC
Labels: requires user input
