### ISSUE TITLE
RuntimeError: should read __file__ to get the source???

### ISSUE THREAD

**Issue by bzsome** [albertosottile/py2exe#38] opened 2020-01-03 06:51 UTC
# package.py
from distutils.core import setup
import py2exe

includes = ["encodings", "sip"]

options = {"py2exe":
               {"compressed": 1,
                "optimize": 2,
                "includes": includes,
                "bundle_files": 1
                }
           }
setup(
    options=options,
    zipfile=None,
    windows=[{"script": "EmailPC.py", "icon_resources": [(1, "icon.ico")]}]
)

# error info

File "package.py", line 44, in <module>
    windows=[{"script": "EmailPC.py", "icon_resources": [(1, "icon.ico")]}]
  File "D:\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Python\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "D:\Python\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 272, in _run
    builder.analyze()
  File "D:\Python\Python37\lib\site-packages\py2exe\runtime.py", line 174, in analyze
    target.analyze(mf)
  File "D:\Python\Python37\lib\site-packages\py2exe\runtime.py", line 75, in analyze
    modulefinder.run_script(self.script)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 88, in run_script
    self._scan_code(mod.__code__, mod)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 428, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 140, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 127, in import_hook
    self._handle_fromlist(module, fromlist, caller)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 198, in _handle_fromlist
    self._gcd_import('{}.{}'.format(mod.__name__, x))
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 276, in _gcd_import
    return self._find_and_load(name)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 391, in _find_and_load
    self._scan_code(module.__code__, module)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 428, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 140, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 127, in import_hook
    self._handle_fromlist(module, fromlist, caller)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 198, in _handle_fromlist
    self._gcd_import('{}.{}'.format(mod.__name__, x))
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 276, in _gcd_import
    return self._find_and_load(name)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 391, in _find_and_load
    self._scan_code(module.__code__, module)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 428, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 140, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 122, in import_hook
    module = self._gcd_import(name)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 276, in _gcd_import
    return self._find_and_load(name)
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 390, in _find_and_load
    if module.__code__:
  File "D:\Python\Python37\lib\site-packages\py2exe\mf3.py", line 708, in __code__
    raise RuntimeError("should read __file__ to get the source???")
RuntimeError: should read __file__ to get the source???

**Comment by albertosottile** [comment] 2020-10-06 17:38
Closing as duplicate of #32

**Closed by albertosottile** 2020-10-06 17:38 UTC
